//Vehicle actions
export const ADD_TO_MYVEHICLES = "ADD_TO_MYVEHICLES";
export const REMOVE_FROM_MYVEHICLES = "REMOVE_FROM_MYVEHICLES";
export const CLEAR_MYVEHICLES = "CLEAR_MYVEHICLES";

//get Makes
export const ADD_TO_MAKES = "ADD_TO_MAKES";
export const FETCH_SUCCESS_MAKES = "FETCH_SUCCESS_MAKES";
export const FETCH_FAILURE_MAKES = "FETCH_FAILURE_MAKES";

//get Models
export const ADD_TO_MODELS = "ADD_TO_MODELS";
export const FETCH_SUCCESS_MODELS = "FETCH_SUCCESS_MODELS";
export const FETCH_FAILURE_MODELS = "FETCH_FAILURE_MODELS";

//get Vehicles
export const ADD_TO_VEHICLES = "ADD_TO_VEHICLES";
export const FETCH_SUCCESS_VEHICLES = "FETCH_SUCCESS_VEHICLES";
export const FETCH_FAILURE_VEHICLES = "FETCH_FAILURE_VEHICLES";

//Loader
export const SET_LOADER = "SET_LOADER";
